# Generated by Django 4.1.6 on 2023-02-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todo_sifati'),
        ('todo_list', '0007_remove_todo_narxi_todo_narx_alter_todo_sifat'),
    ]

    operations = [
    ]
