# Generated by Django 4.1.6 on 2023-02-17 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_merge_20230217_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='sifati',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='sifat',
            field=models.CharField(choices=[('a', 'Alo'), ('b', 'yaxshi'), ('c', 'orta')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
