# Generated by Django 4.1.6 on 2023-02-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_remove_todo_sifati_todo_created_at_alter_todo_sifat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sifat',
            field=models.CharField(choices=[('Alo', 'Alo'), ('yaxshi', 'yaxshi'), ('orta', 'orta')], max_length=50),
        ),
    ]
